"""Write segments.json, chapters.vtt, and a self-contained player.html."""
from __future__ import annotations
import json
from pathlib import Path

WEB = Path(__file__).parent / "web"


def hms(t: float) -> str:
    t = max(0.0, float(t)); h = int(t // 3600); m = int(t % 3600 // 60); s = t % 60
    return f"{h:02d}:{m:02d}:{s:06.3f}"


def write_json(data: dict, out: Path) -> Path:
    out.write_text(json.dumps(data, ensure_ascii=False, indent=1))
    return out


def write_vtt(data: dict, out: Path) -> Path:
    lines = ["WEBVTT", "", "NOTE chapters generated by concert-segmenter", ""]
    for s in data["segments"]:
        lines += [f"{s['id']}", f"{hms(s['start'])} --> {hms(s['end'])}", s.get("title") or s["kind"], ""]
    out.write_text("\n".join(lines))
    return out


def write_player(data: dict, out: Path, video_src: str) -> Path:
    html = (WEB / "player.html").read_text()
    js = (WEB / "dam-segments.js").read_text()
    payload = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    html = html.replace("/*__JS__*/", js).replace("/*__DATA__*/", payload).replace("__VIDEO_SRC__", video_src)
    out.write_text(html)
    return out
